apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapps
  namespace: stolos-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/stolos-cloud/stolos-prod.git'
    path: .
    targetRevision: HEAD
    directory:
      recurse: true
      include: "{*.argoapp.yaml,*.argoapp.yml}"
      exclude: "TEMPLATE/*"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true