apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: stolos-app
  namespace: argocd
spec:
  destination:
    namespace: stolos-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/stolos-cloud/stolos-prod.git'
    path: stolos
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
